apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: mds-server
profiles:
  - name: prepare
    deploy:
      kubectl:
        manifests:
          - k8s/prepare/000_prepare-namespaces.yaml
          - k8s/prepare/010_prepare-strimzi.yaml
          - k8s/prepare/020_public-ingress-nginx.yaml
          - k8s/prepare/021_internal-ingress-nginx.yaml
          - k8s/prepare/030_reloader.yaml
          - k8s/prepare/040_eck-crds.yaml
  - name: mds
    build:
      local:
        concurrency: 8
      artifacts:
        - image: mds-api-gateway-svc
          context: ./
          docker:
            dockerfile: services/go/api-gateway-svc/Dockerfile
        - image: mds-operation-svc
          context: ./
          docker:
            dockerfile: services/go/operation-svc/Dockerfile
        - image: mds-permission-svc
          context: ./
          docker:
            dockerfile: services/go/permission-svc/Dockerfile
        - image: mds-user-svc
          context: ./
          docker:
            dockerfile: services/go/user-svc/Dockerfile
    deploy:
      kubectl:
        manifests:
          - k8s/100_namespaces.yaml
          - k8s/110_logging-eck.yaml
          - k8s/115_fluent-bit.yaml
          - k8s/116_fluent-bit-config.yaml
          - k8s/210_strimzi.yaml
          - k8s/300_kafka.yaml
          - k8s/310_kafka-topics.yaml
          - k8s/500_mds-api-gateway-svc.yaml
          - k8s/501_mds-permission-svc.yaml
          - k8s/510_mds-user-svc.yaml
          - k8s/520_mds-operation-svc.yaml
          - k8s/811_public-ingress.yaml
          - k8s/821_internal-ingress.yaml

