apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: mds-server
profiles:
  - name: prepare
    deploy:
      kubectl:
        manifests:
          - k8s/prepare/000_prepare-namespaces.yaml
          - k8s/prepare/010_prepare-strimzi.yaml
          - k8s/prepare/020_public-ingress-nginx.yaml
          - k8s/prepare/021_internal-ingress-nginx.yaml
          - k8s/prepare/030_reloader.yaml
          - k8s/prepare/040_eck-crds.yaml
  - name: mds
    build:
      local:
        concurrency: 8
      artifacts:
        - image: mds-api-gateway-svc
          context: ./
          docker:
            dockerfile: services/go/api-gateway-svc/Dockerfile
        - image: mds-group-svc
          context: ./
          docker:
            dockerfile: services/go/group-svc/Dockerfile
        - image: mds-logistics-svc
          context: ./
          docker:
            dockerfile: services/go/logistics-svc/Dockerfile
        - image: mds-open-intel-delivery-notifier-svc
          context: ./
          docker:
            dockerfile: services/go/open-intel-delivery-notifier-svc/Dockerfile
        - image: mds-in-app-notifier-svc
          context: ./
          docker:
            dockerfile: services/go/in-app-notifier-svc/Dockerfile
        - image: mds-operation-svc
          context: ./
          docker:
            dockerfile: services/go/operation-svc/Dockerfile
        - image: mds-permission-svc
          context: ./
          docker:
            dockerfile: services/go/permission-svc/Dockerfile
        - image: mds-radio-delivery-svc
          context: ./
          docker:
            dockerfile: services/go/radio-delivery-svc/Dockerfile
        - image: mds-user-svc
          context: ./
          docker:
            dockerfile: services/go/user-svc/Dockerfile
        - image: mds-ws-hub-svc
          context: ./
          docker:
            dockerfile: services/go/ws-hub-svc/Dockerfile
    deploy:
      kubectl:
        manifests:
          - k8s/100_namespaces.yaml
          - k8s/110_logging-eck.yaml
          - k8s/115_fluent-bit.yaml
          - k8s/116_fluent-bit-config.yaml
          - k8s/210_strimzi.yaml
          - k8s/300_kafka.yaml
          - k8s/310_kafka-topics.yaml
          - k8s/320_meilisearch.yaml
          - k8s/500_mds-api-gateway-svc.yaml
          - k8s/501_mds-permission-svc.yaml
          - k8s/510_mds-user-svc.yaml
          - k8s/520_mds-operation-svc.yaml
          - k8s/521_mds-group-svc.yaml
          - k8s/530_mds-logistics-svc.yaml
          - k8s/531_mds-open-intel-delivery-notifier-svc.yaml
          - k8s/540_mds-in-app-notifier-svc.yaml
          - k8s/541_mds-radio-delivery-svc.yaml
          - k8s/811_public-ingress.yaml
          - k8s/821_internal-ingress.yaml
          - k8s/830_mds-ws-hub-svc.yaml

