name: Badges

on:
  push:
    branches:
      - main

jobs:
  lines_of_code:
    runs-on: ubuntu-latest
    name: Lines of Code
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make LoC badge
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        id: badge
        with:
          debug: true
          directory: ./
          badge: ./output/badge-loc.svg
          badge_label: Lines of Code (Go)
          patterns: '**/*.go'

      - name: Count Go unit tests
        id: count_go_unit_tests
        working-directory: ./tools
        run: echo ::set-output name=count::$(count-go-unit-tests.sh)

      - name: Go unit test count badge
        uses: emibcn/badge-action@v1.2.1
        with:
          label: 'Go unit tests'
          status: '≈${{ steps.count_go_unit_tests.outputs.count }}'
          color: '#007837'
          path: ./output/badge-go-unit-test-count.svg

      - name: Deploy to badges branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output
          publish_branch: badges
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'