# Taken from https://github.com/marketplace/actions/sphinx-build.

name: "Pages"

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install pip
          sudo pip install Sphinx==4.5.0
          sudo pip install furo pygments==2.11.2

      - name: Build docs
        run: sphinx-build -b html "./docs" "./docs/_build" -W

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./docs/_build"