# Taken from https://github.com/marketplace/actions/sphinx-build.

name: "Docs Check"

on:
  - push
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install pip
          sudo pip install Sphinx==4.5.0
          sudo pip install furo pygments==2.11.2

      - name: Build docs
        run: sphinx-build -b html "./docs" "./docs/_build" -W
